# Generated by Django 5.1.1 on 2024-09-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Alimentacion', 'Alimentacion'), ('Transporte', 'Transporte'), ('Alojamiento', 'Alojamiento'), ('Entretenimiento', 'Entretenimiento'), ('Salud', 'Salud'), ('Educación', 'Educacion'), ('Impuestos', 'Inpuestos'), ('Seguros', 'Seguros'), ('Servicios públicos', 'Servicios Publicos'), ('Mantenimiento', 'Mantenimiento'), ('Moda', 'Moda'), ('Tecnología', 'Texnologia'), ('Regalos', 'Regalos'), ('Viajes', 'Viajes')], max_length=150)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Salario', 'Salario'), ('Bonificacion', 'Bonificacion'), ('Alquileres', 'Alquiler'), ('Intereses', 'Intereses'), ('Ganancias', 'Ganacias'), ('Pension', 'Pension'), ('Herencia', 'Herencia'), ('Ventas', 'Ventas'), ('Subsidios', 'Subsidios')], max_length=150)),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Incomes',
            },
        ),
    ]
