# Generated by Django 5.1.1 on 2024-09-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('Alimentacion', 'Alimentacion'), ('Transporte', 'Transporte'), ('Alojamiento', 'Alojamiento'), ('Entretenimiento', 'Entretenimiento'), ('Salud', 'Salud'), ('Educación', 'Educacion'), ('Impuestos', 'Inpuestos'), ('Seguros', 'Seguros'), ('Servicios públicos', 'Servicios Publicos'), ('Mantenimiento', 'Mantenimiento'), ('Moda', 'Moda'), ('Tecnología', 'Texnologia'), ('Regalos', 'Regalos'), ('Viajes', 'Viajes'), ('Arriendo', 'Arriendo'), ('Negocio', 'Negocio'), ('Tarjeta de Credito', 'Tarjeta Credito')], max_length=150),
        ),
    ]
