# Generated by Django 5.1.1 on 2024-09-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_alter_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='way_to_pay',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Nequi', 'Nequi'), ('Tarjeta de Credito', 'Tarjeta Credto')], default='Efectivo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='way_to_pay',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Nequi', 'Nequi'), ('Tarjeta de Credito', 'Tarjeta Credto')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('Alimentacion', 'Alimentacion'), ('Transporte', 'Transporte'), ('Alojamiento', 'Alojamiento'), ('Entretenimiento', 'Entretenimiento'), ('Salud', 'Salud'), ('Educación', 'Educacion'), ('Impuestos', 'Inpuestos'), ('Seguros', 'Seguros'), ('Servicios públicos', 'Servicios Publicos'), ('Mantenimiento', 'Mantenimiento'), ('Moda', 'Moda'), ('Tecnología', 'Texnologia'), ('Regalos', 'Regalos'), ('Viajes', 'Viajes'), ('Arriendo', 'Arriendo'), ('Negocio', 'Negocio'), ('Tarjeta de Credito', 'Tarjeta Credito'), ('Mercancias', 'Mercancias'), ('Proveedores', 'Proveedores')], max_length=150),
        ),
    ]
