# Generated by Django 5.1.1 on 2024-10-02 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_expense_way_to_pay_income_way_to_pay_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('Alimentacion', 'Alimentacion'), ('Transporte', 'Transporte'), ('Alojamiento', 'Alojamiento'), ('Entretenimiento', 'Entretenimiento'), ('Salud', 'Salud'), ('Educación', 'Educacion'), ('Impuestos', 'Inpuestos'), ('Seguros', 'Seguros'), ('Servicios', 'Servicios'), ('Mantenimiento', 'Mantenimiento'), ('Moda', 'Moda'), ('Mascotas', 'Mascotas'), ('Tecnología', 'Texnologia'), ('Regalos', 'Regalos'), ('Viajes', 'Viajes'), ('Arriendo', 'Arriendo'), ('Negocio', 'Negocio'), ('Tarjeta de Credito', 'Tarjeta Credito'), ('Mercancias', 'Mercancias'), ('Proveedores', 'Proveedores'), ('Otros', 'Otros')], max_length=150),
        ),
    ]
