# Generated by Django 5.1.1 on 2024-09-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='active',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='passive',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='passive',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
